### PR TITLE
fix get_sha_range failing to find first commit

### PR DESCRIPTION
**Pull request by jcsp**
The previous fix for this issue wasn't working for me:
    the 'base' commit was a valid thing to use, but it was
    not in the scope of what the tool would already have
    fetched while fetching the commits in the PR.
    
    It seems more robust to directly identify the first commit
    based purely on the list of sha1s, rather than relying
    on github's idea of what the base is.

### CODE REVIEW

**Comment by jcsp** [comment]
I originally pushed this before I saw that master already had a fix, but then I found that the fix on master still wasn't working for me, so rebased this.

The issue I saw was on https://github.com/ceph/ceph/pull/12154, where this would happen:
```
$ downstream-cherry-picker https://github.com/ceph/ceph/pull/12154 1415260
INFO: + git cat-file -e 5b402f8a7b5a763852e93cd0a5decd34572f4518^{commit}
fatal: Not a valid object name 5b402f8a7b5a763852e93cd0a5decd34572f4518^{commit}
INFO: First upstream commit not found. Fetching from github.com.
INFO: + git fetch https://github.com/ceph/ceph pull/12154/head
From https://github.com/ceph/ceph
 * branch            refs/pull/12154/head -> FETCH_HEAD
INFO: Cherry-picking https://github.com/ceph/ceph/pull/12154 to ceph-2-rhel-patches (0ee85d9bb0ff9a46cac374de6606f8885ce4c3df)
INFO: + git checkout -b rhbz-1415260
Switched to a new branch 'rhbz-1415260'
INFO: + git -c core.editor=/bin/true cherry-pick -x 5b402f8a7b5a763852e93cd0a5decd34572f4518~..6efad699249ba7c6928193dba111dbb23b606beb
fatal: bad revision '5b402f8a7b5a763852e93cd0a5decd34572f4518~..6efad699249ba7c6928193dba111dbb23b606beb'
Traceback (most recent call last):
  File "/home/jspray/git/downstream-cherry-picker/env/bin/downstream-cherry-picker", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/jspray/git/downstream-cherry-picker/bin/downstream-cherry-picker", line 7, in <module>
    main(sys.argv)
  File "/home/jspray/git/downstream-cherry-picker/downstream_cherry_picker/__init__.py", line 178, in main
    '%s~..%s' % (first, last))
  File "/home/jspray/git/downstream-cherry-picker/downstream_cherry_picker/__init__.py", line 113, in git
    subprocess.check_call(args)
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('git', '-c', 'core.editor=/bin/true', 'cherry-pick', '-x', u'5b402f8a7b5a763852e93cd0a5decd34572f4518~..6efad699249ba7c6928193dba111dbb23b606beb')' returned non-zero exit status 128
```

In this instance the 'base' (5b402f8a7b5a763852e93cd0a5decd34572f4518) was a valid commit, but it hadn't been fetched.  Using the true first commit works though.

**Comment by ktdreyer** [comment]
Sorry about this John, the 1.1.x series is definitely broken in this regard. I'm re-working the test suite to have better coverage with more JSON samples.

**Comment by ktdreyer** [comment]
John, does https://github.com/ktdreyer/downstream-cherry-picker/pull/7 look ok?

**Comment by ktdreyer** [comment]
With PR #7, this is working now.

```
$ downstream-cherry-picker https://github.com/ceph/ceph/pull/12154 1415260
INFO: Cherry-picking https://github.com/ceph/ceph/pull/12154 to ceph-2-rhel-patches (0ee85d9bb0ff9a46cac374de6606f8885ce4c3df)
INFO: + git checkout -b rhbz-1415260
Switched to a new branch 'rhbz-1415260'
INFO: + git -c core.editor=/bin/true cherry-pick -x 6efad699249ba7c6928193dba111dbb23b606beb~..6efad699249ba7c6928193dba111dbb23b606beb
[rhbz-1415260 90a49e7] mds: use projected path construction for access
 Author: Patrick Donnelly <pdonnell@redhat.com>
 Date: Thu Nov 17 21:05:03 2016 -0500
 6 files changed, 35 insertions(+), 71 deletions(-)
INFO: + git checkout ceph-2-rhel-patches
Switched to branch 'ceph-2-rhel-patches'
INFO: + git merge --ff-only rhbz-1415260
Updating 0ee85d9..90a49e7
Fast-forward
 src/mds/CDentry.cc    | 30 ++++---------------------
 src/mds/CDentry.h     |  4 ++--
 src/mds/CDir.cc       |  2 +-
 src/mds/CInode.cc     | 62 ++++++++++++++++++++-------------------------------
 src/mds/CInode.h      |  6 ++---
 src/mds/SessionMap.cc |  2 +-
 6 files changed, 35 insertions(+), 71 deletions(-)
INFO: + git branch -d rhbz-1415260
Deleted branch rhbz-1415260 (was 90a49e7).
```

**Comment by jcsp** [comment]
PR #7 is now implementing this way of finding the first commit

**Pull request closed without merging**
