### PR TITLE
get_sha_range(): find the first commit correctly, add more tests

### PR DESCRIPTION
**Pull request by ktdreyer**
Previous changes broke the ability to properly find the first commit in straightforward PRs.

~~Rather than doing a complicated search for a commit with "base" as the parent, just choose the first commit in the list.~~ EDIT see below

This PR also adds API fixtures from several more Ceph PRs to make sure we have this behavior down correctly.

It also introduces a `new-fixtures.sh` shell script to provide an easy way to quickly import more test data from real-life PRs in case we need to add more test cases here.

### CODE REVIEW

**Comment by jcsp** [comment]
Isn't the github order of commits something wonky?  Or is [0] really guaranteed to be the first, even if [-1] isn't the last?

**Comment by ktdreyer** [comment]
I did an experiment here: https://github.com/ktdreyer/pulltests/pull/1 and it seems that GitHub's "first" commit in its list really is the first commit, even after rebasing.

**Comment by ktdreyer** [comment]
welp, I found a case where this  PR still gets "first" wrong:

1. Create file "A" in commit "A"
2. Create file "B" in commit "B"
3. Rebase so that "B" comes before before "A"
4. GitHub still lists "A" as the first commit

The key seems to be that "A" and "B" should be completely separate files.

**Comment by ktdreyer** [comment]
I've reworked this PR now with several more fixtures.

Rather than doing a search for a commit with "base" as the parent, determine "first" by comparing the parents to the list of commits. In particular, search for a commit that does not have a parent in our current set of commits.
    
Raise `RuntimeError` if we couldn't find a "first" commit this way, or if this method results in more than one "first".
    
Raise `NotImplementedError` if the PR contains a merge commit, because git-cherry-pick is going to bail on this range anyway without the "-m" argument.

**Comment by ktdreyer** [comment]
Tagged v1.2.0 with this change.

**Pull request merged**
